drop table if exists author CASCADE;
drop table if exists event CASCADE;
drop table if exists event_authors CASCADE;
drop table if exists sity CASCADE;
drop table if exists user CASCADE;

create table author(id  bigint generated by default as identity, name varchar(255), primary key (id));
create table event (id  bigint generated by default as identity, date_time    timestamp, description  varchar(255), location varchar(255), name varchar(255), url_img_bg   varchar(255), url_img_logo varchar(255), sity_id bigint, primary key (id));
create table event_authors (event_id bigint not null, authors_id bigint not null, primary key (event_id, authors_id));
create table sity (id bigint generated by default as identity, name varchar(255), url_img_logo varchar(255), primary key (id));
create table user(email varchar(255) not null, activation_code varchar(255), primary key (email));
alter table event add constraint FK8vse8atk0qeuk8wpn9e6ctj9i foreign key (sity_id) references sity;
alter table event_authors add constraint FK9h3j6lpkmej0hia37655cpinr foreign key (authors_id) references author;
alter table event_authors add constraint FK3boplmhg8vg56vaqskotdcvtw foreign key (event_id) references event;

insert into sity (id, name, url_img_logo) values (null, 'Муром', NULL);
insert into event (date_time, description, location, name, sity_id, url_img_bg, url_img_logo) values ('2021-06-05T03:34:27.9895161', 'Lorem Lorem Lorem', 'ул. Воровского 91а', 'Концерт', 1, NULL, NULL);
insert into author (name) values ('Андрей Игнатьев');
insert into event_authors (event_id, authors_id) values (1, 1);

insert into sity (id, name, url_img_logo) values (2, 'Москва', NULL);
insert into event (id, date_time, description, location, name, sity_id, url_img_bg, url_img_logo) values (2, '2021-06-03T03:34:27.9895161', 'Lorem Lorem Lorem', 'Парк горького', 'Прогулка', 2, NULL, NULL);
insert into author (id, name) values (2, 'Вася Кузнецов');
insert into event_authors (event_id, authors_id) values (2, 2);

insert into event (id, date_time, description, location, name, sity_id, url_img_bg, url_img_logo) values (3, '2021-08-03T03:34:27.9895161', 'Lorem Lorem Lorem Lorem Lorem Lorem', 'г.Москва ул. Чертановская', 'Тест', 2, NULL, NULL);
insert into event_authors (event_id, authors_id) values (3, 1);
